name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Rust Rustfmt
        run: cargo fmt --check

  clippy:
    name: Clippy${{ matrix.features.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        features:
          - { features: "" }
          - { name: " (`tls-rustls`)", features: --features tls-rustls }
          - { name: " (`tls-rustls-no-provider`)", features: --features tls-rustls-no-provider }
          - { name: " (`tls-openssl`)", features: --features tls-openssl, openssl: true }
          - { name: " (`--all-features`)", features: --all-features, openssl: true }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenSSL
        if: matrix.features.openssl == true
        run: sudo apt-get install pkg-config libssl-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run Clippy
        run: cargo clippy --all-targets ${{ matrix.features.features }} -- -D warnings
